on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check types
        run: pnpm run tsc:check
      - name: Check lint rules
        run: pnpm run lint:check
      - name: Check format
        run: pnpm run format:check
