name: docker publish

on:
  push:
    branches: [main]
    tags: [v*.*.*] # 手動で作成した時用
  pull_request:
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string

env:
  IMAGE_NAME: om
  # バージョン指定
  # renovate: datasource=github-releases depName=docker/buildx
  BUILDX_VERSION: v0.19.1

jobs:
  docker-publish:
    # release-please によるコミットの時は workflow_call でのみ実行する
    if: ${{ !( github.workflow == 'docker publish' && startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'github-actions[bot]' ) }}
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.metadata.outputs.tags }}
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          version: ${{ env.BUILDX_VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}},value=${{ inputs.tag-name }},enable=${{ !(startsWith(github.ref, 'refs/tags/v0.') || startsWith(inputs.tag-name, 'v0.')) }}
            type=edge,branch=main

      - name: Delete org.opencontainers.image.licenses label
        id: labels
        run: |
          cat << EOS >> "$GITHUB_OUTPUT"
          labels<<EOF
          $(echo '${{ steps.metadata.outputs.labels }}' | sed '/^org.opencontainers.image.licenses=/d')
          EOF
          EOS

      - id: build-push
        name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.labels.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - if: ${{ github.event_name != 'pull_request' }}
        name: Display image digest
        env:
          NAME: ${{ fromJson(steps.build-push.outputs.metadata)['image.name'] }}
          DIGEST: ${{ fromJson(steps.build-push.outputs.metadata)['containerimage.digest'] }}
        run: |
          name=$(cut --delimiter=',' --fields=1 <<< "$NAME")

          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$name@$DIGEST" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
